unlock with resource and id as argument
joanvila/aioredlock pull request #84
Opened 2020-10-23 15:36 UTC by ar4hc

simple solution for #83 

(and a typo...)

2020-10-23 16:48 UTC, gtmanfred requested changes
I think I would prefer to have a `get` function on the manager, that would allow for getting just one lock, similar to the `get_all_active_locks` function, and then leave `unlock()` unmodified.  This would allow you to get the lock object first, and pass it in.

2020-11-06 11:56 UTC, ar4hc commented
sry, didn't look here in a while... :/ 
Where is that "get_all_active_locks" function...?

And as the unlock unpack the Lock object and uses the resource and identifier wouldn't that mean some extra steps...?
Creating a new Lock object just to have it  unpacked again in the next step looks a bit convoluted to me...

2020-11-06 12:28 UTC, ar4hc commented
the `create_lock` method (more `fake_lock`...) would look like this:
```python
    async def create_lock(resource, lock_identifier, lock_timeout=10.0):

        lease_time = lock_timeout or self.internal_lock_timeout
        lock = Lock(self, resource, lock_identifier, lease_time, valid=True)
        return lock
```

perhaps add a check of the lock before with `is_locked`, but that's the gist of it.

i don't like it... :(

2020-11-06 15:18 UTC, gtmanfred commented
We have other places where we make round trips to the database to make sure locks exist.  I would rather add that function, because i can see it be useful in other places.

You could also retrieve the ttl left on a lock to know when it is going to expire as opposed to setting it based on what is passed in.

Also, if we add another redis script that checks the identifier that is passed in, and returns the TTL, that would give us all the information we need to recreate the lock on one round trip.

2020-11-06 15:21 UTC, gtmanfred commented
Something like this ```
    CHECK_LOCK_SCRIPT = """
    local identifier = redis.call('get', KEYS[1])
    if not identifier then
        return redis.error_reply('ERROR')
    if identifier == ARGV[1] then
        return redis.call("TTL", KEYS[1])
    else
        return redis.error_reply('ERROR')
    end"""
```

2020-11-10 15:45 UTC, ar4hc commented
get_lock_ttl is a bit over complicated for that task, i think, but here you go... :)

2020-11-11 14:18 UTC, gtmanfred commented on tests/ut/test_redis.py
> +        print(res)
looks like this is left behind.

2020-11-11 14:18 UTC, gtmanfred commented on tests/ut/test_redis.py
> +        # assert 0
cleanup

2020-11-11 14:18 UTC, gtmanfred commented on tests/ut/test_redis.py
> +        # assert 0
cleanup

2020-11-11 14:18 UTC, gtmanfred commented on tests/ut/test_redis.py
> +        print(ttl)
cleanup

2020-11-11 14:18 UTC, gtmanfred commented on tests/ut/test_redis.py
> +        assert pool.execute.call_count == len(self.script_names)
nice

2020-11-11 14:18 UTC, gtmanfred commented on aioredlock/algorithm.py
> +logger.setLevel(logging.DEBUG)
cleanup

2020-11-11 14:18 UTC, gtmanfred commented on aioredlock/algorithm.py
> +    async def unlock(self, resource_or_lock, lock_identifier=None):
I think that we should still just be passing in the lock here, now that you can get a recreated lock.  This was the whole point of adding `get_lock` to leave `unlock` unmodified.

2020-11-11 14:19 UTC, gtmanfred commented
The rest of this looks good, just some cleanup. and removing the changes from the `unlock` function please.

2020-11-13 17:45 UTC, gtmanfred approved these changes
Looks great!

Thanks for making those changes.

2020-11-13 17:45 UTC, merged

2020-11-17 12:26 UTC, ar4hc commented
:)

2020-11-17 13:13 UTC, gtmanfred commented
You should be all set to go, this is released in v0.6.0, which i am pushing out now.

Thank you for the contribution!